alter table public.ip_assets
  add column if not exists status text default 'active',
  add column if not exists last_latency_ms integer,
  add column if not exists last_speed_kbps integer,
  add column if not exists last_tested_at timestamptz,
  add column if not exists last_ip text;

create table if not exists public.proxy_test_results (
  id bigint generated by default as identity primary key,
  proxy_id bigint references public.ip_assets(id) on delete cascade,
  host text,
  port int,
  is_reachable boolean,
  latency_ms int,
  download_speed_kbps int,
  ip_address text,
  error_message text,
  tested_at timestamptz default now()
);

alter table public.proxy_test_results enable row level security;

create policy "Users can view their own proxy test results"
  on public.proxy_test_results for select
  using (
    exists (
      select 1 from public.ip_assets
      where ip_assets.id = proxy_test_results.proxy_id
      and (ip_assets.owner = auth.uid() or public.is_admin() or public.has_module_permission('ip', 'read'))
    )
  );

create policy "Users can insert their own proxy test results"
  on public.proxy_test_results for insert
  with check (
    exists (
      select 1 from public.ip_assets
      where ip_assets.id = proxy_test_results.proxy_id
      and (ip_assets.owner = auth.uid() or public.is_admin() or public.has_module_permission('ip', 'write'))
    )
  );
